import { execFileSync } from 'child_process';
import { writeFileSync, mkdirSync, existsSync, unlinkSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import config from '../common/config.js';

// Native macOS adapter — the Darwin counterpart of adapter-win.js. Same public
// API (launchInstance / createNewInstance / isProcessAlive / hideWindow /
// showWindow / isWindowVisible / killInstance) so the platform dispatcher
// (adapter.js) can swap it in transparently; instances.js never knows the OS.
//
// Model (researched 2026-06-20; AppleScript facts verified against the Terminal
// scripting dictionary + Apple dev-forum usage — some are version-dependent and
// flagged below for first-run verification on the target Mac):
//   - A managed instance is a Claude Code CLI running in its OWN Terminal.app
//     window, spawned via `do script` (osascript). `do script` (no target) opens
//     a NEW window and returns a TAB; we resolve its window and cache the window
//     id as the durable handle (analogous to the Win32 MainWindowHandle).
//   - The instance's PID is captured EXACTLY: the per-instance launcher does
//     `echo $$ >pidfile; exec claude …`, and `exec` replaces the shell in place,
//     so claude inherits that PID. Liveness/kill then work by PID (process.kill).
//   - hide/show map to the window's `visible` property (keeps the process
//     running); foreground adds `activate` + `frontmost`. kill terminates the
//     PID's process group and closes the window by matching the tab's tty.
//
// Caveat (documented in STATUS.md): driving Terminal via AppleScript triggers a
// one-time macOS Automation (TCC) consent prompt — a human must approve it once
// at the console; until then launches fail (null pid). Nothing here can
// pre-approve it without a signed bundle + MDM, which is out of scope.
//
// KNOWN PARITY GAP (STATUS.md KI-8): Windows removes the window's SC_CLOSE menu
// item so the X can never kill a managed instance. Terminal.app exposes no
// scriptable equivalent, so a user CAN close an instance window (red button /
// Cmd-W). Two things bound it: Terminal's default "prompt before closing" a
// window with a running process asks for confirmation, and the subcontroller
// treats the resulting dead pid as a crash and RELAUNCHES the instance
// (permanence holds, up to CRASH_RETRY_MAX). A real but bounded difference.

const EXECKEE_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const HOOK_PATH = join(EXECKEE_ROOT, 'src', 'instance-hook.js');
const INSTANCE_SETTINGS_FILE = join(config.DATA_DIR, 'instance-settings.json');

const MAC_HELPER = join(config.DATA_DIR, '_mac-helper.sh');
const LAUNCHER_DIR = join(config.DATA_DIR, 'launchers');
const PID_DIR = join(config.DATA_DIR, 'pids');

// Session-scoped settings injected at launch via `claude --settings <file>`.
// Carries the SessionStart + UserPromptSubmit hook that captures the live
// session id and handles in-instance hide/close. The user's global ~/.claude is
// never modified. (Kept byte-identical to adapter-win.js's version on purpose —
// the hook command `node "<path>"` is itself cross-platform — so the two
// adapters stay independent and editing one never risks the other.)
let settingsWritten = false;
function ensureInstanceSettings() {
  if (settingsWritten) return INSTANCE_SETTINGS_FILE;
  const settings = {
    hooks: {
      SessionStart: [
        { hooks: [{ type: 'command', command: `node "${HOOK_PATH}"` }] },
      ],
      UserPromptSubmit: [
        { hooks: [{ type: 'command', command: `node "${HOOK_PATH}"` }] },
      ],
    },
  };
  writeFileSync(INSTANCE_SETTINGS_FILE, JSON.stringify(settings, null, 2), 'utf-8');
  settingsWritten = true;
  return INSTANCE_SETTINGS_FILE;
}

// The bash helper that runs the AppleScript. Mirrors _win32-helper.ps1: one
// script, dispatched by an Action argument. Window control is osascript;
// liveness (alive) is done in Node (process.kill), exactly as on Windows.
// NOTE for maintainers: this is written verbatim to disk, so it must contain NO
// JS `${...}` interpolation and NO backslash escapes — keep it a plain template.
const MAC_HELPER_CONTENT = `#!/bin/bash
# Execkee macOS window/process helper (generated by adapter-mac.js — do not edit;
# it is rewritten on launch). Actions: launch | hide | show | visible | kill.
set -u

ACTION="$1"

case "$ACTION" in
  launch)
    # $2 = path to the per-instance launcher; $3 = pidfile the launcher writes.
    LAUNCHER="$2"
    PIDFILE="$3"
    # Resolve the new window from the returned tab. On any miss, leave theId 0
    # (null handle) rather than guessing the front window — a wrong guess would
    # cross-wire hide/show for an unrelated instance; a null handle fails safe.
    WID=$(osascript 2>/dev/null <<OSA
tell application "Terminal"
  set theTab to do script "/bin/sh '$LAUNCHER'"
  delay 0.2
  set theId to 0
  try
    set theWin to first window whose tabs contains theTab
    set theId to id of theWin
    set visible of theWin to false
  end try
  return theId
end tell
OSA
)
    [ -z "$WID" ] && WID=0
    # The launcher does \`echo $$ >pidfile; exec claude\`, so the pidfile holds
    # claude's real pid once it is up. Poll up to ~12s, matching the Win handle poll.
    PID=""
    i=0
    while [ "$i" -lt 48 ]; do
      if [ -s "$PIDFILE" ]; then
        P=$(tr -dc '0-9' < "$PIDFILE")
        if [ -n "$P" ] && kill -0 "$P" 2>/dev/null; then PID="$P"; break; fi
      fi
      sleep 0.25
      i=$((i + 1))
    done
    # Launch failed (no live pid) but a window opened: close the orphan, report none.
    if [ -z "$PID" ] && [ "$WID" != "0" ]; then
      osascript >/dev/null 2>&1 <<OSA
tell application "Terminal" to close (window id $WID) saving no
OSA
      WID=0
    fi
    # Pipe-delimited so an empty pid never shifts the window id into the pid field.
    echo "$PID|$WID"
    ;;
  hide)
    WID="$2"
    case "$WID" in ''|*[!0-9]*) echo no-window; exit 0 ;; esac
    if osascript >/dev/null 2>&1 <<OSA
tell application "Terminal" to set visible of window id $WID to false
OSA
    then echo ok; else echo no-window; fi
    ;;
  show)
    WID="$2"
    case "$WID" in ''|*[!0-9]*) echo no-window; exit 0 ;; esac
    if osascript >/dev/null 2>&1 <<OSA
tell application "Terminal"
  set visible of window id $WID to true
  activate
  set frontmost of window id $WID to true
end tell
OSA
    then echo ok; else echo no-window; fi
    ;;
  visible)
    WID="$2"
    case "$WID" in ''|*[!0-9]*) echo false; exit 0 ;; esac
    V=$(osascript 2>/dev/null <<OSA
tell application "Terminal" to get visible of window id $WID
OSA
)
    if [ "$V" = "true" ]; then echo true; else echo false; fi
    ;;
  kill)
    # Capture tty + pgid BEFORE killing (so we can close the window after), then
    # SIGTERM->SIGKILL the process group, then close the matching Terminal window.
    PID="$2"
    case "$PID" in ''|*[!0-9]*) echo ok; exit 0 ;; esac
    TTY=$(ps -o tty= -p "$PID" 2>/dev/null | tr -d ' ')
    PGID=$(ps -o pgid= -p "$PID" 2>/dev/null | tr -d ' ')
    kill -TERM "$PID" 2>/dev/null
    [ -n "$PGID" ] && kill -TERM "-$PGID" 2>/dev/null
    sleep 0.3
    kill -KILL "$PID" 2>/dev/null
    [ -n "$PGID" ] && kill -KILL "-$PGID" 2>/dev/null
    if [ -n "$TTY" ]; then
      DEV="/dev/$TTY"
      osascript >/dev/null 2>&1 <<OSA
tell application "Terminal"
  repeat with w in windows
    repeat with t in tabs of w
      try
        if tty of t is "$DEV" then close w saving no
      end try
    end repeat
  end repeat
end tell
OSA
    fi
    echo ok
    ;;
  *)
    echo "unknown-action" >&2
    exit 1
    ;;
esac
`;

let helperWritten = false;
function ensureHelper() {
  if (helperWritten) return;
  for (const d of [config.DATA_DIR, LAUNCHER_DIR, PID_DIR]) {
    if (!existsSync(d)) mkdirSync(d, { recursive: true });
  }
  writeFileSync(MAC_HELPER, MAC_HELPER_CONTENT, 'utf-8');
  helperWritten = true;
}

function runHelper(args, timeout = 30_000) {
  ensureHelper();
  try {
    return execFileSync('/bin/bash', [MAC_HELPER, ...args], {
      encoding: 'utf-8',
      timeout,
    }).trim();
  } catch (err) {
    console.error(`[adapter-mac] Helper error (${args[0]}):`, err.message);
    return '';
  }
}

// Single-quote a value for safe inclusion in a /bin/sh command line.
function shq(s) {
  return `'${String(s).replace(/'/g, `'\\''`)}'`;
}

function doLaunch(instanceId, claudeArgs, projectPath) {
  // Defense-in-depth: instanceId becomes a filename AND the launcher path is
  // embedded inside the launch AppleScript, so a stray quote/metachar would be an
  // injection vector. Legit ids are inst-<base36> / wh-<host>; reject anything
  // outside a strict allowlist rather than risk it. (instanceId arrives from the
  // controller over the WS link, which is otherwise unauthenticated.)
  if (!/^[A-Za-z0-9._-]{1,64}$/.test(String(instanceId))) {
    console.error(`[adapter-mac] refusing to launch: unsafe instanceId ${JSON.stringify(instanceId)}`);
    return { pid: null, windowHandle: null };
  }
  ensureHelper();
  const cwd = projectPath || process.cwd();
  const settings = ensureInstanceSettings();
  // Optional native Remote Control (EXECKEE_REMOTE_CONTROL=1, on by default).
  // Instance launches carry no positional prompt, so --remote-control never
  // swallows one as a session name; it degrades gracefully if RC is ineligible.
  const rc = config.REMOTE_CONTROL_ENABLED ? ['--remote-control'] : [];
  const allArgs = [...claudeArgs, ...rc, '--settings', settings];

  const pidfile = join(PID_DIR, `${instanceId}.pid`);
  const launcher = join(LAUNCHER_DIR, `${instanceId}.command`);
  try { if (existsSync(pidfile)) unlinkSync(pidfile); } catch {}

  // The launcher: set cwd + the env the in-instance hook needs, record the pid,
  // then `exec` so claude keeps that exact pid (clean liveness/kill).
  const claudeCmd = ['claude', ...allArgs].map(shq).join(' ');
  const launcherContent = [
    '#!/bin/sh',
    `cd ${shq(cwd)} || exit 1`,
    `export EXECKEE_INSTANCE_ID=${shq(instanceId)}`,
    `export EXECKEE_DATA_DIR=${shq(config.DATA_DIR)}`,
    `echo $$ > ${shq(pidfile)}`,
    `exec ${claudeCmd}`,
    '',
  ].join('\n');
  writeFileSync(launcher, launcherContent, 'utf-8');

  const out = runHelper(['launch', launcher, pidfile], 60_000);
  // Pipe-delimited (see helper): an empty pid yields "|<wid>" or "|0", never
  // shifting the window id into the pid field.
  const [pidStr, widStr] = out.split('|');
  const pid = parseInt(pidStr, 10) || null;
  const wid = (widStr || '').trim();
  const windowHandle = wid && wid !== '0' ? wid : null;
  return { pid, windowHandle };
}

export function launchInstance(instanceId, sessionId, projectPath, options = {}) {
  // A session-less instance cannot be --resume'd; launch it fresh (mirrors win / KI-1).
  if (!sessionId) return createNewInstance(instanceId, projectPath);
  const claudeArgs = ['--resume', sessionId];
  if (options.skipPermissions) claudeArgs.push('--dangerously-skip-permissions');
  const result = doLaunch(instanceId, claudeArgs, projectPath);
  console.log(`[adapter-mac] Launched ${instanceId}: pid=${result.pid} win=${result.windowHandle}${options.skipPermissions ? ' [full permissions]' : ''}`);
  return result;
}

export function createNewInstance(instanceId, projectPath) {
  const result = doLaunch(instanceId, [], projectPath);
  console.log(`[adapter-mac] Created ${instanceId}: pid=${result.pid} win=${result.windowHandle}`);
  return result;
}

export function isProcessAlive(pid) {
  if (!pid) return false;
  // Native, signal-0 liveness — runs every cycle, must not spawn a process.
  try { process.kill(pid, 0); return true; } catch { return false; }
}

// Window ids and pids are always bare integers; validate before handing them to
// the helper so a malformed value (e.g. a poisoned tracking record arriving over
// the WS link) can never be interpolated into an AppleScript heredoc.
function numericHandle(h) {
  return /^[0-9]+$/.test(String(h)) ? String(h) : null;
}

export function hideWindow(windowHandle) {
  const h = numericHandle(windowHandle);
  if (!h) return false;
  return runHelper(['hide', h]) === 'ok';
}

export function showWindow(windowHandle) {
  const h = numericHandle(windowHandle);
  if (!h) return false;
  return runHelper(['show', h]) === 'ok';
}

export function isWindowVisible(windowHandle) {
  const h = numericHandle(windowHandle);
  if (!h) return false;
  return runHelper(['visible', h]).toLowerCase() === 'true';
}

export function killInstance(pid) {
  const p = numericHandle(pid);
  if (!p) return false;
  return runHelper(['kill', p]) === 'ok';
}
